export const SYSTEM_LIMITS = {
  MAX_LOGIN_ATTEMPTS: 5,
  TOKEN_EXPIRY_SECONDS: 3600,
  MAX_TRANSACTION_AMOUNT: 1000000,
  MAX_RETRY_ATTEMPTS: 3,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;