export const ERROR_CODES = {
  UNKNOWN_ERROR: "ERR_UNKNOWN",
  VALIDATION_ERROR: "ERR_VALIDATION",
  AUTH_FAILED: "ERR_AUTH_FAILED",
  TOKEN_EXPIRED: "ERR_TOKEN_EXPIRED",
  INSUFFICIENT_FUNDS: "ERR_INSUFFICIENT_FUNDS",
  WALLET_NOT_FOUND: "ERR_WALLET_NOT_FOUND",
  TRANSACTION_FAILED: "ERR_TRANSACTION_FAILED",
  DATABASE_ERROR: "ERR_DATABASE",
  KAFKA_ERROR: "ERR_KAFKA",
} as const;